# System info
os: linux
dist: xenial

# Blacklist
branches:
  only:
    - master

# Environment variables
env:
  global:
    - GH_REPO_NAME: libzed
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile-travis-ci
    - GH_REPO_REF: github.com/ZacharyWesterman/libzed.git

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

# Build your code e.g. by calling make
script:
  - make dynamic
  - make install
  - make examples

language:
  - cpp

# Generate and deploy documentation
after_success:
  - cd $TRAVIS_BUILD_DIR
  - chmod +x deployDocumentation.sh
  - ./deployDocumentation.sh
