name: Enforce Style Guide

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  style-guide:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v6
  
    - name: Update apt repository
      run: sudo apt-get update

    - name: Require clang-format
      run: sudo apt install -y clang-format

    - name: Verify that code is formatted
      run: make try-format
